import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import NextTopLoader from "nextjs-toploader";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${plusJakartaSans.variable} ${geistMono.variable} h-full antialiased`}
      style={{
        "--font-body": "var(--font-plus-jakarta)",
        "--font-display": "var(--font-plus-jakarta)",
        "--font-sans": "var(--font-plus-jakarta)",
      } as React.CSSProperties}
    >
      <body className="min-h-full flex flex-col bg-primary text-primary transition-colors duration-200">
        <ThemeProvider>
          <NextTopLoader color="var(--color-brand-600)" showSpinner={false} shadow="0 0 10px var(--color-brand-600),0 0 5px var(--color-brand-600)" />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}





